<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generator" nsURI="http://www.yakindu.org/base/generator/Generator"
    nsPrefix="generator">
  <eClassifiers xsi:type="ecore:EClass" name="CodeElement" eSuperTypes="../../org.yakindu.base.types/model/base.ecore#//NamedElement ../../org.yakindu.base.types/model/base.ecore#//DocumentedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//CodeElement" eOpposite="#//CodeElement/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//CodeElement"
        eOpposite="#//CodeElement/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceFileGen" eSuperTypes="#//CodeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassGen" eSuperTypes="#//CodeElement #//AccessRestricted">
    <eOperations name="addConstructor">
      <eParameters name="parameters" upperBound="-1" eType="#//ParameterGen"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" eType="#//ClassGen"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="#//ClassGen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodGen" eSuperTypes="#//CodeElement #//AccessRestricted">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterGen"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass ../../org.yakindu.base.types/model/types.ecore#//TypeSpecifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessRestricted"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableGen" eSuperTypes="#//CodeElement #//AccessRestricted ../../org.yakindu.base.types/model/types.ecore#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterGen" eSuperTypes="#//CodeElement ../../org.yakindu.base.types/model/types.ecore#//TypedElement"/>
</ecore:EPackage>
