package org.yakindu.base.generator.java.test

import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith
import org.yakindu.base.generator.java.test.util.AbstractJavaGeneratorTest
import org.yakindu.base.generator.java.test.util.JavaGeneratorTestInjectorProvider

@RunWith(XtextRunner)
@InjectWith(JavaGeneratorTestInjectorProvider)
class SourceFileTest extends AbstractJavaGeneratorTest {
	@Test
	def simpleSourceFileTest() {
		val sourceFile = helper.createSourceFileGen("TestClass.java")
		val testClass = helper.createClassGen("TestClass", "public")
		sourceFile.children.add(testClass)

		val exp = '''
			/*
			 * File TestClass.java
			 * Generated by the YAKINDU Code Generator
			 */
			
			public class TestClass {
			}
			
		'''
		generatesTo(exp, sourceFile)
	}
}
